### ISSUE TITLE
Add support for other navigation keys

### ISSUE THREAD

**Issue by boolieman** [WICG/focus-ring#59] opened 2017-10-18 15:27 UTC
I have found your library and first off, its AMAZING! Thank you so much, I would like to propose adding support however for other keystrokes such as arrow and spacebar keys so that the interactions work as expected via all input element in a complex form.  Is this part of the spec that was proposed? If so I would be more than happy to add handlers for these events in a PR.

**Comment by robdodson** [comment] 2017-10-19 00:09
Duplicate of #54. We're discussing if we need to make changes over there :)

**Closed by robdodson** 2017-10-19 00:09 UTC
