### ISSUE TITLE
No focus styling on certain elements with Firefox

### ISSUE THREAD

**Issue by erikkroes** [WICG/focus-ring#14] opened 2017-03-29 08:52 UTC
When going through the demo at https://wicg.github.io/focus-ring/demo/ with the tab-key, the focus styling is not visible on the element with `role="textbox"`, the `<div>`'s with `tabindex=0`, and the `<select>`'s with a set `size`.

**Comment by robdodson** [comment] 2017-03-29 14:36
Are you on mac or windows?

I put together a jsbin to test https://jsbin.com/vefalubezi/edit?html,output

On mac it looks like they use a couple different focus styles.

![image](https://cloud.githubusercontent.com/assets/1066253/24460039/e961a336-1451-11e7-997b-5eb1310524ce.png)

![image](https://cloud.githubusercontent.com/assets/1066253/24460046/f10d7092-1451-11e7-9679-35ee181a34a1.png)

![image](https://cloud.githubusercontent.com/assets/1066253/24460057/f98ef3a8-1451-11e7-9148-67cd24dfd8c6.png)

So in the demo it mostly uses the blue focus ring, but in some places they revert to using a very subtle dashed outline. Are you seeing the same results? If so then the demo is working correctly and Firefox just has an inconsistent native focus ring.

**Comment by robdodson** [comment] 2017-04-06 11:13
Going to close this issue but happy to reopen if there's a follow up response.

**Closed by robdodson** 2017-04-06 11:13 UTC

**Comment by erikkroes** [comment] 2017-04-10 13:57
Sorry for the late reply. I'm seeing the same result. So that's just a situation for which focus-ring is not a solution? A shame, but good to know. Thanks!

**Comment by robdodson** [comment] 2017-04-10 15:44
Well in that situation you DO want to see an outline, because you're navigating by keyboard, so this is working as intended I think.

**Comment by xirclebox** [comment] 2018-10-02 21:05
I just tested the plugin with various browsers on the Mac and noticed that the focus rings in Safari aren't present on the radios and sliders. Sad face but not a deal breaker. 
https://wicg.github.io/focus-visible/demo/

**Comment by robdodson** [comment] 2018-10-03 05:30
I just checked the demo in Safari. It looks like radios show a focus ring if you tab to them. Sliders do not, but I think that's a Safari quirk. Tabbing to [this slider](https://jsbin.com/buyihefagi/edit?html,js,output) doesn't show a focus indicator on my machine.
